config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :players
  resources :people do
     collection do
     get "temp", as: :temp
     end

    end
  resources :testers
  resources :coders
  resources :students
  resources :developers do
   collection do
     get "newindex", as: :newindex
   end
  end
  resources :employees do
    collection  do 
     get "structure", as: :structure
    end
  end
  resources :comments
  resources :posts
  devise_for :users

  root 'developers#newindex'

end

app/models/coder.rb
class Coder < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/developer.rb
class Developer < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/tester.rb
class Tester < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :comments
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  def structure
    @emp = params[:manager] ? Employee.where(manager: params[:manager]) : []
    @manager = Employee.first
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:name, :manager)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @blog_comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coders_helper.rb
module CodersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee) do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :manager %><br>
    <%= f.text_field :manager %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Examples</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Desc</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.name %></td>
        <td><%= example.desc %></td>
        <td><%= link_to 'Show', example %></td>
        <td><%= link_to 'Edit', examples_path(example) %></td>
        <td><%= link_to 'Destroy', example, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Example', new_example_path %>
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="panel-group" id="panel-184085">
        
        <div class="panel panel-default">
          
          <div class="panel-heading">
             <a class="panel-title" data-toggle="collapse" data-parent="#panel-184085" href="#panel-element-215703">Collapsible Group Item #1</a>
          </div>
        

          <div id="panel-element-215703" class="panel-collapse collapse in">
            <div class="panel-body">
              Anim pariatur cliche...
            </div>
          </div>
          
        </div>














        <div class="panel panel-default">
          <div class="panel-heading">
             <a class="panel-title" data-toggle="collapse" data-parent="#panel-184085" href="#panel-element-203691">Collapsible Group Item #2</a>
          </div>
          <div id="panel-element-203691" class="panel-collapse collapse">
            <div class="panel-body">
              Anim pariatur cliche...
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Manager:</strong>
  <%= @employee.manager %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/employees/structure.html.erb
<%=link_to "#{@manager.manager}", structure_employees_path(manager: @manager.manager)%>
<br/>
<br/>
<br/>
<% @emp.each do | e | %>
	<%#=e.name%>
	<%=link_to "#{e.name}", structure_employees_path(manager: e.name)%>
<% end %>