config/routes.rb
Rails.application.routes.draw do
  resources :products
  resources :players
  resources :people do
     collection do
     get "temp", as: :temp
     end

    end
  resources :testers
  resources :coders
  resources :students
  resources :developers do
   collection do
     get "newindex", as: :newindex
   end
  end
  resources :employees do
    collection  do 
     get "structure", as: :structure
    end
  end
  resources :comments
  resources :posts
  devise_for :users

  root 'developers#newindex'

end

app/models/coder.rb
class Coder < ActiveRecord::Base
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :user
	belongs_to :post
end

app/models/developer.rb
class Developer < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/models/player.rb
class Player < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	has_many :comments
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/models/tester.rb
class Tester < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

         has_many :posts
         has_many :comments
end

app/controllers/coders_controller.rb
class CodersController < ApplicationController
  before_action :set_coder, only: [:show, :edit, :update, :destroy]

  # GET /coders
  # GET /coders.json
  def index
    @coders = Coder.all
    @coder = Coder.new
  end

  # GET /coders/1
  # GET /coders/1.json
  def show
  end

  # GET /coders/new
  def new
    @coder = Coder.new
  end

  # GET /coders/1/edit
  def edit
  end

  # POST /coders
  # POST /coders.json
  def create
    @coder = Coder.new(coder_params)

    respond_to do |format|
      if @coder.save
        format.html { redirect_to coders_path }
        format.json { render :show, status: :created, location: @coder }
      else
        format.html { render :new }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coders/1
  # PATCH/PUT /coders/1.json
  def update
    respond_to do |format|
      if @coder.update(coder_params)
        format.html { redirect_to @coder, notice: 'Coder was successfully updated.' }
        format.json { render :show, status: :ok, location: @coder }
      else
        format.html { render :edit }
        format.json { render json: @coder.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coders/1
  # DELETE /coders/1.json
  def destroy
    @coder.destroy
    respond_to do |format|
      format.html { redirect_to coders_url, notice: 'Coder was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coder
      @coder = Coder.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coder_params
      params.require(:coder).permit(:name, :age)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comment = Comment.new
    @blog_comments = @post.comments
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:name, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coders_helper.rb
module CodersHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/testers_helper.rb
module TestersHelper
end

app/views/coders/_codertable.html.erb
 <p id="notice"><%= notice %></p>

                            <h1>Listing Coders</h1>

                            <table>
                              <thead>
                                <tr>
                                  <th>Name</th>
                                  <th>Age</th>
                                  <th colspan="3"></th>
                                </tr>
                              </thead>

                              <tbody>
                                <% @coders.each do |coder| %>
                                  <tr>
                                    <td><%= coder.name %></td>
                                    <td><%= coder.age %></td>
                                    <td><%= link_to 'Show', coder %></td>
                                    <td><%= link_to 'Edit', coders_path(coder) %></td>
             <td><a class="panel-title" data-toggle="collapse" data-parent="#panel-67518" href="#panel-element-559773" <%= link_to 'Edit', coders_path(coder) %> </a></a></td>

                                    <td><%= link_to 'Destroy', coder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                                  </tr>
                                <% end %>
                              </tbody>
                            </table>
                            <br>

app/views/coders/_form.html.erb
<%= form_for(@coder) do |f| %>
  <% if @coder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coder.errors.count, "error") %> prohibited this coder from being saved:</h2>

      <ul>
      <% @coder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coders/edit.html.erb
<h1>Editing Coder</h1>

<%= render 'form' %>

<%= link_to 'Show', @coder %> |
<%= link_to 'Back', coders_path %>

app/views/coders/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
      <div class="panel-group" id="panel-67518">
       

        <div class="panel panel-default">
          <div class="panel-heading">
             <a class="panel-title" data-toggle="collapse" data-parent="#panel-67518" href="#panel-element-559771">Collapsible Group Item #1.1</a>
          </div>
          
          <div id="panel-element-559771" class="panel-collapse collapse ">
            <div class="panel-body">
              <br>
              <%= render 'codertable' %>
              <br>
             <a class="panel-title" data-toggle="collapse" data-parent="#panel-67518" href="#panel-element-559772">New Coder</a>
             <br>
            </div>
          </div>

          <div id="panel-element-559772" class="panel-collapse collapse">
            <div class="panel-body">
              <%= render 'form' %>
            </div>
          </div>

          <div id="panel-element-559773" class="panel-collapse collapse">
            <div class="panel-body">
              <%= render 'form' %>
            </div>
          </div>

        </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/coders/new.html.erb
<h1>New Coder</h1>

<%= render 'form' %>

<%= link_to 'Back', coders_path %>

app/views/coders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @coder.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @coder.age %>
</p>

<%= link_to 'Edit', edit_coder_path(@coder) %> |
<%= link_to 'Back', coders_path %>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @post.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= render "comments/form" %>

<% @blog_comments.each do | c | %>
	<%=c.user.email%> says <%= c.review%><br/>

<% end %>